server:
  port: 8081

spring:
  datasource:
    # ??? localhost ?????????3306 ? MySQL ??????
    url: jdbc:mysql://localhost:3306/attendance_system?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    # !!!??????? 123456 ??????? MySQL ??????
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver

# ?????????????????? Java ????????????
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
