server:
  port: 8081

# 自定义文件上传路径配置
file-upload:
  # Windows 开发环境下写这个
  path: D:/uploads/

spring:
  datasource:
    # ??? localhost ?????????3306 ? MySQL ??????
    url: jdbc:mysql://localhost:3306/attendance_system?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    # !!!??????? 123456 ??????? MySQL ??????
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver

    hikari:
      maximum-pool-size: 100  # 最大连接池大小，建议与 JMeter 线程数匹配
      minimum-idle: 10       # 最小空闲连接数
      idle-timeout: 30000    # 空闲连接超时时间（毫秒）
      connection-timeout: 20000 # 等待连接的最大时间（毫秒）

# ?????????????????? Java ????????????
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true